import { chromium } from 'playwright';
import path from 'path';
const URL = 'file://' + path.resolve('/home/user/-/dist/forest_expedition.html');
const b = await chromium.launch(); const ctx = await b.newContext({ viewport: { width: 1280, height: 720 } }); const p = await ctx.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message)); p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
await p.goto(URL); await p.waitForTimeout(300);
await p.evaluate(() => { const G = window.GAME.Game; G.settings.seenHints = { field: 1, map: 1, battle: 1, charge: 1, break: 1, explore: 1 }; G.scenes.title.start(4242); G.go('map'); });
await p.waitForTimeout(300);
await p.screenshot({ path: '/home/user/-/test-output/ex_map.png' });
await p.click('.map-node.reachable >> nth=0'); await p.waitForTimeout(100);
await p.screenshot({ path: '/home/user/-/test-output/ex_map_info.png' });
await p.click('#btn-node-go'); await p.waitForTimeout(1500);
await p.screenshot({ path: '/home/user/-/test-output/ex_walk.png' });
const sc = async () => p.evaluate(() => window.GAME.Game.sceneName);
for (let i = 0; i < 60 && (await sc()) === 'explore'; i++) await p.waitForTimeout(200);
console.log('scene', await sc());
await p.waitForTimeout(1500);
await p.screenshot({ path: '/home/user/-/test-output/ex_battle.png' });
await p.evaluate(() => { window.GAME.Game.debug.simMult = 6; });
await p.waitForTimeout(3000);
await p.screenshot({ path: '/home/user/-/test-output/ex_battle2.png' });
console.log(await p.evaluate(() => { const S = window.GAME.Game.scene; return S.sim ? JSON.stringify({ W: S.sim.W, cam: Math.round(S.camX), heroes: S.sim.heroes.map((h) => Math.round(h.x)), en: S.sim.enemies.map((e) => Math.round(e.x)) }) : window.GAME.Game.sceneName; }));
console.log('errors', errs);
await b.close();
