// v0.59 미지의 적·패턴·환경·정찰 확인: node tools/dev/foes59_shot.mjs → test-output/f59_*.png
import { chromium } from 'playwright';
import path from 'path';
const b = await chromium.launch(); const p = await (await b.newContext({ viewport: { width: 1280, height: 720 } })).newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
await p.goto('file://' + path.resolve('dist/forest_expedition.html')); await p.waitForTimeout(400);
await p.evaluate(() => { const G = window.GAME.Game; G.settings.seenHints = { field: 1, battle: 1, break: 1, charge: 1, crush: 1, dungeon: 1, map: 1 }; G.scenes.title.start(8); G.profile.scouts = 2; window.GAME.enterDungeon(G.run); G.run.dungeon.env = 'dark';
  G.go('battle', { node: { stage: 3, row: 0, type: 'battle', waves: [['orc', 'goblin_shaman', 'wraith']] } }); });
await p.waitForTimeout(1200); await p.screenshot({ path: 'test-output/f59_unknown.png' });
await p.evaluate(() => { const s = window.GAME.Game.scene.sim; const o = s.enemies.find((e) => e.key === 'orc'); o.patCd.reflect = 0; });
await p.waitForTimeout(900); await p.screenshot({ path: 'test-output/f59_reflect.png' });
await p.waitForTimeout(2500); await p.screenshot({ path: 'test-output/f59_reveal.png' });
await p.evaluate(() => { const G = window.GAME.Game; G.run.dungeon.env = 'embers'; G.go('battle', { node: { stage: 3, row: 0, type: 'battle', waves: [['ogre', 'goblin_archer']] } }); });
await p.waitForTimeout(800); await p.evaluate(() => { const s = window.GAME.Game.scene.sim; const o = s.enemies.find((e) => e.key === 'ogre'); o.hardenT = 4; const a = s.enemies.find((e) => e.key === 'goblin_archer'); a.patCd.acid = 0; s.envT = 99; });
await p.waitForTimeout(1500); await p.screenshot({ path: 'test-output/f59_harden_acid.png' });
await p.evaluate(() => { const G = window.GAME.Game; G.run.dungeon = null; G.go('field'); }); await p.waitForTimeout(400);
await p.click('#btn-codex'); await p.waitForTimeout(300); await p.screenshot({ path: 'test-output/f59_codex.png' }); await p.click('#codex-close');
await p.evaluate(() => window.GAME.openDungeonGate('cave', window.GAME.Game.scene)); await p.waitForTimeout(300);
await p.screenshot({ path: 'test-output/f59_gate.png' });
console.log(errs); await b.close();
