// 빠른 스모크: 주요 화면 스크린샷 + 콘솔 에러 수집
import { chromium } from 'playwright';
import path from 'path';
const out = process.argv[2] || '.';
const vp = { width: +(process.argv[3] || 1280), height: +(process.argv[4] || 720) };
const b = await chromium.launch();
const p = await b.newPage({ viewport: vp, hasTouch: true, deviceScaleFactor: 1 });
const errs = [];
p.on('pageerror', (e) => errs.push('pageerror ' + e.message));
p.on('console', (m) => { if (m.type() === 'error') errs.push('console ' + m.text()); });
await p.goto('file://' + path.resolve('dist/forest_expedition.html'));
await p.waitForTimeout(500);
const shot = async (n) => p.screenshot({ path: `${out}/${n}.png` });
await shot('01_title');
await p.click('#btn-start'); await p.waitForTimeout(300);
await shot('02_field_hint');
await p.click('#hint-ok'); await p.waitForTimeout(1200);
await shot('03_field');
await p.click('#btn-party'); await p.waitForTimeout(300);
await shot('03b_party');
await p.click('#ps-ok'); await p.waitForTimeout(200);
await p.click('#btn-automove'); await p.waitForTimeout(4500);
await shot('04_field_portal');
await p.click('#portal-yes'); await p.waitForTimeout(400);
await p.click('#hint-ok'); await p.waitForTimeout(300);
await shot('05_map');
await p.click('.map-node.reachable'); await p.waitForTimeout(200);
await shot('06_map_info');
await p.click('#btn-node-go'); await p.waitForTimeout(300);
await shot('07_after_move');
await p.click('#pb-start'); await p.waitForTimeout(300);
await p.click('#hint-ok'); await p.waitForTimeout(2500);
await shot('08_battle');
await p.click('#btn-manual');
await p.waitForSelector('#btn-skill-s2.ready', { timeout: 15000 });
await p.click('#btn-skill-s2'); await p.waitForTimeout(200);
await shot('09_target_single');
await p.click('#btn-t-confirm'); await p.waitForTimeout(600);
await shot('10_after_cast');
await p.click('.bport[data-hero=bori]');
await p.waitForSelector('#btn-skill-s2.ready', { timeout: 20000 });
await p.click('#btn-skill-s2'); await p.waitForTimeout(200);
const bb = await p.locator('#cv').boundingBox(); const sx = bb.width/960;
await p.mouse.move(bb.x+300*sx, bb.y+330*sx); await p.mouse.down(); await p.mouse.move(bb.x+360*sx, bb.y+335*sx, {steps:5});
await shot('11_target_area');
await p.mouse.up();
await p.click('#btn-t-confirm'); await p.waitForTimeout(350);
await shot('12_arrowrain');
await p.click('#btn-auto'); await p.click('#btn-speed');
await p.waitForTimeout(6000);
await shot('13_battle_later');
const lastErr = await p.evaluate(() => window.GAME.Game.lastError);
console.log('errors:', errs, lastErr || '');
await b.close();
